=== alesandrani/LMSGI/WsLMSGI-master/05_DTD/01_DTD_Pelicula.dtd
<!ELEMENT pelicula (titulo,fecha,actores,director?)>

<!-- Definimos los atributos de la pelicula -->
<!ATTLIST pelicula id ID #REQUIRED>
<!ATTLIST pelicula categoria (accion | terror | humor | sci-fi) #REQUIRED>
<!ATTLIST pelicula calificacion CDATA #IMPLIED>
<!ATTLIST pelicula edad CDATA "18">
<!ATTLIST pelicula empresa CDATA #FIXED "Walt Disney">

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT actores (actor+)>

<!ELEMENT actor (nombre,edad,super_estrella?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT super_estrella EMPTY>

<!ELEMENT director (#PCDATA)>

=== alesandrani/LMSGI/WsLMSGI-master/05_DTD/01_DTD_PeliculaDTDExterno.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE pelicula SYSTEM "01_DTD_Pelicula.dtd">
<pelicula id="GAL1" categoria="sci-fi">
    <titulo>La guerra de las galaxias</titulo>
    <fecha>22/07/1977</fecha>
    <actores>
        <actor>
            <nombre>Luke Skywalker</nombre>
            <edad>29</edad>
        </actor>
        <actor>
            <nombre>Han Solo</nombre>
            <edad>39</edad>
            <super_estrella />
        </actor>
    </actores>
    <director>George Lucas</director>
</pelicula>
